//
// Created by mojucheng on 2023/2/20.
//

#ifndef TEST_PLUGIN_LIB_EXPORT_DEFINES_H
#define TEST_PLUGIN_LIB_EXPORT_DEFINES_H

#include "lib_export_common.h"

#ifdef SOME_EXPORTS
#define EXPORT_CLASS DLL_EXPORT_CLASS_DECL
#define EXPORT_API DLL_EXPORT_DECL
#define EXPORT_API_C DLL_EXPORT_C_DECL
#else
#define EXPORT_CLASS DLL_IMPORT_CLASS_DECL
#define EXPORT_API DLL_IMPORT_DECL
#define EXPORT_API_C DLL_IMPORT_C_DECL
#endif
#endif //TEST_PLUGIN_LIB_EXPORT_DEFINES_H
